# Configuration file used to place important settings
# Flag to test if the file was correct
is_ok: 1
# Checkerboard size. Number of inward corners (height, width)
checkerboard size: [8,6]
# Size of the square of checkerboard in cm
square size: 1
# Flag to do calibration
do calibration: 0
# Flag to fiducial mark
do fiducial mark: 0
# Flag to put 3D frame
put 3D frame: 1
# Calibration image folder
calibration folder: fotosCalibration
# Image with fiducial mark
name fiducial image: FiducialMarkA4DifferentIDsSmall.png
# Directory of the fiducial image
directory fiducial image: Images
# Source images to put a 3D object
name 3d image: eu.jpg
# Directory for source image
directory 3d image: Images
# Data file name
data file name: calibration_data.yaml
# Directory for a data file
directory data file: Data