# Configuration file used to place important settings
# Flag to test if the file was correct
is_ok: 1
# Checkerboard size. Number of inward corners (height, width)
checkerboard size: [8,6]
# Size of the square of checkerboard in cm
square size: 1
# Flag to do calibration
do calibration: 1
# Flag to fiducial mark
do fiducial mark: 0
# Calibration image folder
calibration folder: fotosCalibration